### ISSUE TITLE
IPFIX OOM

### ISSUE THREAD

**Issue by glowa001** [VerizonDigital/vflow#97]
OOM in decodeSet() 

Correct IPFIX packet generated by pmacct makes infinite loop in decodeSet() and as a result goes out of memory by appending empty data []DecodedField to msg.DataSets.

Below IPFIX packet correctly decoded by wireshark and templates:
[FLOWS]
```
Cisco NetFlow/IPFIX
    Version: 10
    Length: 288
    Timestamp: Feb  4, 2019 14:27:04.000000000 CET
    FlowSequence: 95526
    Observation Domain Id: 0
    Set 1 [id=1024] (2 flows)
        FlowSet Id: (Data) (1024)
        FlowSet Length: 120
        [Template Frame: 13]
        Flow 1
            [Duration: 1.816000000 seconds (milliseconds)]
                StartTime: Feb  4, 2019 14:27:02.769000000 CET
                EndTime: Feb  4, 2019 14:27:04.585000000 CET
            Octets: 840
            Packets: 10
            IPVersion: 4
            InputInt: 0
            OutputInt: 0
            Direction: Ingress (0)
            SrcAddr: 10.0.2.15
            DstAddr: 216.58.215.99
            SrcPort: 0
            DstPort: 0
            IP ToS: 0x00
            TCP Flags: 0x00
            Protocol: ICMP (1)
        Flow 2
            [Duration: 1.816000000 seconds (milliseconds)]
                StartTime: Feb  4, 2019 14:27:02.769000000 CET
                EndTime: Feb  4, 2019 14:27:04.585000000 CET
            Octets: 840
            Packets: 10
            IPVersion: 4
            InputInt: 0
            OutputInt: 0
            Direction: Ingress (0)
            SrcAddr: 216.58.215.99
            DstAddr: 10.0.2.15
            SrcPort: 0
            DstPort: 0
            IP ToS: 0x00
            TCP Flags: 0x00
            Protocol: ICMP (1)
        Padding: 0000
    Set 2 [id=2048] (1 flows)
        FlowSet Id: (Data) (2048)
        FlowSet Length: 88
        [Template Frame: 13]
        Flow 1
            [Duration: 0.000000000 seconds (milliseconds)]
            Octets: 189
            Packets: 1
            IPVersion: 6
            InputInt: 0
            OutputInt: 0
            Direction: Ingress (0)
            SrcAddr: fe80::1f0c:7220:b25e:ccbd
            DstAddr: ff02::fb
            IP ToS: 0x00
            SrcPort: 5353
            DstPort: 5353
            TCP Flags: 0x00
            Protocol: UDP (17)
        Padding: 000000
    Set 3 [id=1024] (1 flows)
        FlowSet Id: (Data) (1024)
        FlowSet Length: 64
        [Template Frame: 13]
        Flow 1
            [Duration: 0.000000000 seconds (milliseconds)]
            Octets: 169
            Packets: 1
            IPVersion: 4
            InputInt: 0
            OutputInt: 0
            Direction: Ingress (0)
            SrcAddr: 10.0.2.15
            DstAddr: 224.0.0.251
            SrcPort: 5353
            DstPort: 5353
            IP ToS: 0x00
            TCP Flags: 0x00
            Protocol: UDP (17)
        Padding: 000000
```

[TEMPLATES]
````
Cisco NetFlow/IPFIX
    Version: 10
    Length: 288
    Timestamp: Feb  4, 2019 14:26:48.000000000 CET
    FlowSequence: 95510
    Observation Domain Id: 0
    Set 1 [id=2] (Data Template): 1024
        FlowSet Id: Data Template (V10 [IPFIX]) (2)
        FlowSet Length: 68
        Template (Id = 1024, Count = 15)
            Template Id: 1024
            Field Count: 15
            Field (1/15): flowEndMilliseconds
            Field (2/15): flowStartMilliseconds
            Field (3/15): BYTES
            Field (4/15): PKTS
            Field (5/15): IP_PROTOCOL_VERSION
            Field (6/15): INPUT_SNMP
            Field (7/15): OUTPUT_SNMP
            Field (8/15): DIRECTION
            Field (9/15): IP_SRC_ADDR
            Field (10/15): IP_DST_ADDR
            Field (11/15): L4_SRC_PORT
            Field (12/15): L4_DST_PORT
            Field (13/15): IP_TOS
            Field (14/15): TCP_FLAGS
            Field (15/15): PROTOCOL
    Set 2 [id=2] (Data Template): 1025
        FlowSet Id: Data Template (V10 [IPFIX]) (2)
        FlowSet Length: 68
        Template (Id = 1025, Count = 15)
            Template Id: 1025
            Field Count: 15
            Field (1/15): flowEndMilliseconds
            Field (2/15): flowStartMilliseconds
            Field (3/15): BYTES
            Field (4/15): PKTS
            Field (5/15): IP_PROTOCOL_VERSION
            Field (6/15): INPUT_SNMP
            Field (7/15): OUTPUT_SNMP
            Field (8/15): DIRECTION
            Field (9/15): IP_SRC_ADDR
            Field (10/15): IP_DST_ADDR
            Field (11/15): L4_SRC_PORT
            Field (12/15): L4_DST_PORT
            Field (13/15): IP_TOS
            Field (14/15): TCP_FLAGS
            Field (15/15): PROTOCOL
    Set 3 [id=2] (Data Template): 2048
        FlowSet Id: Data Template (V10 [IPFIX]) (2)
        FlowSet Length: 68
        Template (Id = 2048, Count = 15)
            Template Id: 2048
            Field Count: 15
            Field (1/15): flowEndMilliseconds
            Field (2/15): flowStartMilliseconds
            Field (3/15): BYTES
            Field (4/15): PKTS
            Field (5/15): IP_PROTOCOL_VERSION
            Field (6/15): INPUT_SNMP
            Field (7/15): OUTPUT_SNMP
            Field (8/15): DIRECTION
            Field (9/15): IPV6_SRC_ADDR
            Field (10/15): IPV6_DST_ADDR
            Field (11/15): IP_TOS
            Field (12/15): L4_SRC_PORT
            Field (13/15): L4_DST_PORT
            Field (14/15): TCP_FLAGS
            Field (15/15): PROTOCOL
    Set 4 [id=2] (Data Template): 2049
        FlowSet Id: Data Template (V10 [IPFIX]) (2)
        FlowSet Length: 68
        Template (Id = 2049, Count = 15)
            Template Id: 2049
            Field Count: 15
            Field (1/15): flowEndMilliseconds
            Field (2/15): flowStartMilliseconds
            Field (3/15): BYTES
            Field (4/15): PKTS
            Field (5/15): IP_PROTOCOL_VERSION
            Field (6/15): INPUT_SNMP
            Field (7/15): OUTPUT_SNMP
            Field (8/15): DIRECTION
            Field (9/15): IPV6_SRC_ADDR
            Field (10/15): IPV6_DST_ADDR
            Field (11/15): IP_TOS
            Field (12/15): L4_SRC_PORT
            Field (13/15): L4_DST_PORT
            Field (14/15): TCP_FLAGS
            Field (15/15): PROTOCOL
````

You can try it yourself using my sample code:
````
package main

import (
	"bytes"
	"fmt"
	"net"

	"github.com/VerizonDigital/vflow/ipfix"
)

//real payloads copypasta
var payload = []byte{0, 10, 1, 32, 92, 88, 61, 168, 0, 1, 117, 38, 0, 0, 0, 0, 4, 0, 0, 120, 0, 0, 1, 104, 184, 176, 218, 137, 0, 0, 1, 104, 184, 176, 211, 113, 0, 0, 0, 0, 0, 0, 3, 72, 0, 0, 0, 0, 0, 0, 0, 10, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 2, 15, 216, 58, 215, 99, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 104, 184, 176, 218, 137, 0, 0, 1, 104, 184, 176, 211, 113, 0, 0, 0, 0, 0, 0, 3, 72, 0, 0, 0, 0, 0, 0, 0, 10, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 216, 58, 215, 99, 10, 0, 2, 15, 0, 0, 0, 0, 0, 0, 1, 0, 0, 8, 0, 0, 88, 0, 0, 1, 104, 184, 172, 62, 242, 0, 0, 1, 104, 184, 172, 62, 242, 0, 0, 0, 0, 0, 0, 0, 189, 0, 0, 0, 0, 0, 0, 0, 1, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 254, 128, 0, 0, 0, 0, 0, 0, 31, 12, 114, 32, 178, 94, 204, 189, 255, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 251, 0, 20, 233, 20, 233, 0, 17, 0, 0, 0, 4, 0, 0, 64, 0, 0, 1, 104, 184, 172, 62, 242, 0, 0, 1, 104, 184, 172, 62, 242, 0, 0, 0, 0, 0, 0, 0, 169, 0, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 2, 15, 224, 0, 0, 251, 20, 233, 20, 233, 0, 0, 17, 0, 0, 0}
var payloadTemplate = []byte{0, 10, 1, 32, 92, 88, 61, 152, 0, 1, 117, 22, 0, 0, 0, 0, 0, 2, 0, 68, 4, 0, 0, 15, 0, 153, 0, 8, 0, 152, 0, 8, 0, 1, 0, 8, 0, 2, 0, 8, 0, 60, 0, 1, 0, 10, 0, 4, 0, 14, 0, 4, 0, 61, 0, 1, 0, 8, 0, 4, 0, 12, 0, 4, 0, 7, 0, 2, 0, 11, 0, 2, 0, 5, 0, 1, 0, 6, 0, 1, 0, 4, 0, 1, 0, 2, 0, 68, 4, 1, 0, 15, 0, 153, 0, 8, 0, 152, 0, 8, 0, 1, 0, 8, 0, 2, 0, 8, 0, 60, 0, 1, 0, 10, 0, 4, 0, 14, 0, 4, 0, 61, 0, 1, 0, 8, 0, 4, 0, 12, 0, 4, 0, 7, 0, 2, 0, 11, 0, 2, 0, 5, 0, 1, 0, 6, 0, 1, 0, 4, 0, 1, 0, 2, 0, 68, 8, 0, 0, 15, 0, 153, 0, 8, 0, 152, 0, 8, 0, 1, 0, 8, 0, 2, 0, 8, 0, 60, 0, 1, 0, 10, 0, 4, 0, 14, 0, 4, 0, 61, 0, 1, 0, 27, 0, 16, 0, 28, 0, 16, 0, 5, 0, 1, 0, 7, 0, 2, 0, 11, 0, 2, 0, 6, 0, 1, 0, 4, 0, 1, 0, 2, 0, 68, 8, 1, 0, 15, 0, 153, 0, 8, 0, 152, 0, 8, 0, 1, 0, 8, 0, 2, 0, 8, 0, 60, 0, 1, 0, 10, 0, 4, 0, 14, 0, 4, 0, 61, 0, 1, 0, 27, 0, 16, 0, 28, 0, 16, 0, 5, 0, 1, 0, 7, 0, 2, 0, 11, 0, 2, 0, 6, 0, 1, 0, 4, 0, 1}

func decode(dstIP net.IP, payload []byte, templates ipfix.MemCache) {
	d := ipfix.NewDecoder(dstIP, payload)
	decodedMsg, err := d.Decode(templates)
	if err != nil {
		fmt.Println("IPFIX decoding error: ", err)
		if decodedMsg == nil {
			return
		}
	}

	if len(decodedMsg.DataSets) > 0 {
		b, err := decodedMsg.JSONMarshal(new(bytes.Buffer))
		if err != nil {
			fmt.Println(err)
			return
		}
		fmt.Println(string(b))
	}
}

func main() {
	defer fmt.Println("end _ TestOOM")
	fmt.Println("TestOOM")

	fmt.Println(len(payload))
	fmt.Println(len(payloadTemplate))

	templates := ipfix.GetCache("")
	dstIP := net.IP{127, 0, 0, 1}

	decode(dstIP, payloadTemplate, templates)
	// for {
	decode(dstIP, payload, templates)
	// }
}
````

[Output after few seconds]
```` 
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x7c2cb0, 0x16)
        /usr/lib/go-1.10/src/runtime/panic.go:616 +0x81
runtime.sysMap(0xc5ab7c0000, 0xb38f0000, 0x411900, 0x9d3b78)
        /usr/lib/go-1.10/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0x9baa00, 0xb38f0000, 0x4407ba)
        /usr/lib/go-1.10/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0x9baa00, 0x59c76, 0x0)
        /usr/lib/go-1.10/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0x9baa00, 0x59c76, 0x9d3b88, 0x0)
        /usr/lib/go-1.10/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0x9baa00, 0x59c76, 0xffffffffffff0100, 0x7fbbd77fddb8)
        /usr/lib/go-1.10/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
        /usr/lib/go-1.10/src/runtime/mheap.go:753 +0x4d
runtime.(*mheap).alloc(0x9baa00, 0x59c76, 0x7fbbd7010100, 0x425120)
        /usr/lib/go-1.10/src/runtime/mheap.go:752 +0x8a
runtime.largeAlloc(0xb38ec000, 0x450001, 0xc420526000)
        /usr/lib/go-1.10/src/runtime/malloc.go:826 +0x94
runtime.mallocgc.func1()
        /usr/lib/go-1.10/src/runtime/malloc.go:721 +0x46
runtime.systemstack(0x0)
        /usr/lib/go-1.10/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
        /usr/lib/go-1.10/src/runtime/proc.go:1175

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/lib/go-1.10/src/runtime/asm_amd64.s:363 fp=0xc420047a70 sp=0xc420047a68 pc=0x453c20
runtime.mallocgc(0xb38ec000, 0x72da60, 0x72ea9f01, 0xc420526000)
        /usr/lib/go-1.10/src/runtime/malloc.go:720 +0x8a2 fp=0xc420047b10 sp=0xc420047a70 pc=0x411e12
runtime.growslice(0x72da60, 0xc420526000, 0x5fc3955, 0x5fc3955, 0x5fc3956, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/runtime/slice.go:179 +0x14a fp=0xc420047b78 sp=0xc420047b10 pc=0x4407ba
github.com/VerizonDigital/vflow/ipfix.(*Decoder).decodeSet(0xc420047e70, 0xc420152200, 0x20, 0x20, 0xc4200a1880, 0x800001, 0xc420088040)
        /home/glowa/go/src/github.com/VerizonDigital/vflow/ipfix/decoder.go:226 +0x4af fp=0xc420047d78 sp=0xc420047b78 pc=0x6e2f8f
github.com/VerizonDigital/vflow/ipfix.(*Decoder).Decode(0xc420047e70, 0xc420152200, 0x20, 0x20, 0xc4200a1840, 0x0, 0x0)
        /home/glowa/go/src/github.com/VerizonDigital/vflow/ipfix/decoder.go:123 +0x157 fp=0xc420047e00 sp=0xc420047d78 pc=0x6e28f7
main.decode(0xc42009a884, 0x4, 0x4, 0x97f460, 0x120, 0x120, 0xc420152200, 0x20, 0x20)
        /home/glowa/***/cmd/test/main.go:16 +0xe4 fp=0xc420047ec0 sp=0xc420047e00 pc=0x6fa3b4
main.main()
        /home/glowa/***/cmd/test/main.go:46 +0x2c1 fp=0xc420047f88 sp=0xc420047ec0 pc=0x6fa861
runtime.main()
        /usr/lib/go-1.10/src/runtime/proc.go:198 +0x212 fp=0xc420047fe0 sp=0xc420047f88 pc=0x42c8a2
runtime.goexit()
        /usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420047fe8 sp=0xc420047fe0 pc=0x456771
exit status 2
````

In my investigation i noticed that vflow lib has problem with decoding multisets flows received as single ipfix packet. What's worse decoder is not resistant to malformed ipfix packets and is exposed to denial of service.

Please take a look at debug output from my sample code with added debug prints in decodeSet and decodeData below
[Code]
````
func (d *Decoder) decodeSet(mem MemCache, msg *Message) error {

	fmt.Println("decodeSet")

	startCount := d.reader.ReadCount()

	fmt.Printf("startCount = %v\n", startCount)

	setHeader := new(SetHeader)
	fmt.Printf("setHeader = %+v\n", *setHeader)
	if err := setHeader.unmarshal(d.reader); err != nil {
		return err
	}
	if setHeader.Length < 4 {
		return io.ErrUnexpectedEOF
	}
	fmt.Printf("2 setHeader = %+v\n", *setHeader)
	var tr TemplateRecord
	var err error
	// This check is somewhat redundant with the switch-clause below, but the retrieve() operation should not be executed inside the loop.
	if setHeader.SetID > 255 {
		var ok bool
		tr, ok = mem.retrieve(setHeader.SetID, d.raddr)
		if !ok {
			select {
			case rpcChan <- RPCRequest{
				ID: setHeader.SetID,
				IP: d.raddr,
			}:
			default:
			}
			err = nonfatalError(fmt.Errorf("%s unknown ipfix template id# %d",
				d.raddr.String(),
				setHeader.SetID,
			))
		}
	}

	// the next set should be greater than 4 bytes otherwise that's padding
	for err == nil && setHeader.Length > uint16(d.reader.ReadCount()-startCount) && d.reader.Len() > 4 {
		fmt.Printf("3 setHeader = %+v\n", *setHeader)

		fmt.Printf("setHeader.Length = %v \n ", setHeader.Length)
		fmt.Printf("d.reader.ReadCount() = %v \n ", d.reader.ReadCount())
		fmt.Printf("d.reader.Len() = %v \n ", d.reader.Len())

		if setId := setHeader.SetID; setId == 2 || setId == 3 {
			// Template record or template option record

			// Check if only padding is left in this set. A template id of zero indicates padding bytes, which MUST be zero.
			templateId, err := d.reader.PeekUint16()
			if err == nil && templateId == 0 {
				break
			}

			tr := TemplateRecord{}
			if setId == 2 {
				err = tr.unmarshal(d.reader)
			} else {
				err = tr.unmarshalOpts(d.reader)
			}
			if err == nil {
				mem.insert(tr.TemplateID, d.raddr, tr)
			}
		} else if setId >= 4 && setId <= 255 {
			// Reserved set, do not read any records
			break
		} else {
			fmt.Printf("msg: %v\n", *msg)
			fmt.Printf("setHeader.SetID: %v\n", setId)

			// Data set
			var data []DecodedField
			data, err = d.decodeData(tr)
			if err == nil {
				fmt.Printf("data: %v\n", data)
				msg.DataSets = append(msg.DataSets, data)
			}

			// if len(data) == 0 {
			// 	panic("len = 0")
			// }
		}

		fmt.Printf(" 2 d.reader.ReadCount() = %v \n ", d.reader.ReadCount())
	}

	// Skip the rest of the set in order to properly continue with the next set
	// This is necessary if the set is padded, has a reserved set ID, or a nonfatal error occurred
	leftoverBytes := setHeader.Length - uint16(d.reader.ReadCount()-startCount)
	if leftoverBytes > 0 {
		_, skipErr := d.reader.Read(int(leftoverBytes))
		if skipErr != nil {
			err = skipErr
		}
	}
	return err
}
````
````
func (d *Decoder) decodeData(tr TemplateRecord) ([]DecodedField, error) {
	var (
		fields []DecodedField
		err    error
		b      []byte
	)
	r := d.reader

	fmt.Printf("len(tr.ScopeFieldSpecifiers)  = %v \n", len(tr.ScopeFieldSpecifiers))
	fmt.Printf("len(tr.FieldSpecifiers)  = %v \n", len(tr.FieldSpecifiers))
...
...
...
````

[Debug]
````
TestOOM
288
288
decodeSet
startCount = 16
setHeader = {SetID:0 Length:0}
2 setHeader = {SetID:2 Length:68}
3 setHeader = {SetID:2 Length:68}
setHeader.Length = 68
 d.reader.ReadCount() = 20
 d.reader.Len() = 268
  2 d.reader.ReadCount() = 84
 decodeSet
startCount = 84
setHeader = {SetID:0 Length:0}
2 setHeader = {SetID:2 Length:68}
3 setHeader = {SetID:2 Length:68}
setHeader.Length = 68
 d.reader.ReadCount() = 88
 d.reader.Len() = 200
  2 d.reader.ReadCount() = 152
 decodeSet
startCount = 152
setHeader = {SetID:0 Length:0}
2 setHeader = {SetID:2 Length:68}
3 setHeader = {SetID:2 Length:68}
setHeader.Length = 68
 d.reader.ReadCount() = 156
 d.reader.Len() = 132
  2 d.reader.ReadCount() = 220
 decodeSet
startCount = 220
setHeader = {SetID:0 Length:0}
2 setHeader = {SetID:2 Length:68}
3 setHeader = {SetID:2 Length:68}
setHeader.Length = 68
 d.reader.ReadCount() = 224
 d.reader.Len() = 64
  2 d.reader.ReadCount() = 288
 decodeSet
startCount = 16
setHeader = {SetID:0 Length:0}
2 setHeader = {SetID:1024 Length:120}
3 setHeader = {SetID:1024 Length:120}
setHeader.Length = 120
 d.reader.ReadCount() = 20
 d.reader.Len() = 268
 msg: {127.0.0.1 {10 288 1549286824 95526 0} []}
setHeader.SetID: 1024
len(tr.ScopeFieldSpecifiers)  = 0
len(tr.FieldSpecifiers)  = 15
data: [{153 1549286824585 0} {152 1549286822769 0} {1 840 0} {2 10 0} {60 4 0} {10 0 0} {14 0 0} {61 0 0} {8 10.0.2.15 0} {12 216.58.215.99 0} {7 0 0} {11 0 0} {5 0 0} {6 [0] 0} {4 1 0}]
 2 d.reader.ReadCount() = 77
 3 setHeader = {SetID:1024 Length:120}
setHeader.Length = 120
 d.reader.ReadCount() = 77
 d.reader.Len() = 211
 msg: {127.0.0.1 {10 288 1549286824 95526 0} [[{153 1549286824585 0} {152 1549286822769 0} {1 840 0} {2 10 0} {60 4 0} {10 0 0} {14 0 0} {61 0 0} {8 10.0.2.15 0} {12 216.58.215.99 0} {7 0 0} {11 0 0} {5 0 0} {6 [0] 0} {4 1 0}]]}
setHeader.SetID: 1024
len(tr.ScopeFieldSpecifiers)  = 0
len(tr.FieldSpecifiers)  = 15
data: [{153 1549286824585 0} {152 1549286822769 0} {1 840 0} {2 10 0} {60 4 0} {10 0 0} {14 0 0} {61 0 0} {8 216.58.215.99 0} {12 10.0.2.15 0} {7 0 0} {11 0 0} {5 0 0} {6 [0] 0} {4 1 0}]
 2 d.reader.ReadCount() = 134
 3 setHeader = {SetID:1024 Length:120}
setHeader.Length = 120
 d.reader.ReadCount() = 134
 d.reader.Len() = 154
 msg: {127.0.0.1 {10 288 1549286824 95526 0} [[{153 1549286824585 0} {152 1549286822769 0} {1 840 0} {2 10 0} {60 4 0} {10 0 0} {14 0 0} {61 0 0} {8 10.0.2.15 0} {12 216.58.215.99 0} {7 0 0} {11 0 0} {5 0 0} {6 [0] 0} {4 1 0}] [{153 1549286824585 0} {152 1549286822769 0} {1 840 0} {2 10 0} {60 4 0} {10 0 0} {14 0 0} {61 0 0} {8 216.58.215.99 0} {12 10.0.2.15 0} {7 0 0} {11 0 0} {5 0 0} {6 [0] 0} {4 1 0}]]}
setHeader.SetID: 1024
len(tr.ScopeFieldSpecifiers)  = 0
len(tr.FieldSpecifiers)  = 15
data: [{153 8796098789376 0} {152 101534041545768960 0} {1 101534041545768960 0} {2 12386304 0} {60 0 0} {10 0 0} {14 17170432 0} {61 0 0} {8 0.0.0.0 0} {12 0.0.254.128 0} {7 0 0} {11 0 0} {5 0 0} {6 [0] 0} {4 31 0}]
 2 d.reader.ReadCount() = 191
 err decode set = can not read the data
decodeSet
startCount = 191
setHeader = {SetID:0 Length:0}
2 setHeader = {SetID:3186 Length:8370}
err decode set = can not read the data
decodeSet
startCount = 195
setHeader = {SetID:0 Length:0}
2 setHeader = {SetID:24268 Length:48639}
err decode set = can not read the data
decodeSet
startCount = 199
setHeader = {SetID:0 Length:0}
err decode set = unexpected EOF
decodeSet
startCount = 203
setHeader = {SetID:0 Length:0}
err decode set = unexpected EOF
decodeSet
startCount = 207
setHeader = {SetID:0 Length:0}
err decode set = unexpected EOF
decodeSet
startCount = 211
setHeader = {SetID:0 Length:0}
2 setHeader = {SetID:0 Length:64256}
3 setHeader = {SetID:0 Length:64256}
setHeader.Length = 64256
 d.reader.ReadCount() = 215
 d.reader.Len() = 73
 msg: {127.0.0.1 {10 288 1549286824 95526 0} [[{153 1549286824585 0} {152 1549286822769 0} {1 840 0} {2 10 0} {60 4 0} {10 0 0} {14 0 0} {61 0 0} {8 10.0.2.15 0} {12 216.58.215.99 0} {7 0 0} {11 0 0} {5 0 0} {6 [0] 0} {4 1 0}] [{153 1549286824585 0} {152 1549286822769 0} {1 840 0} {2 10 0} {60 4 0} {10 0 0} {14 0 0} {61 0 0} {8 216.58.215.99 0} {12 10.0.2.15 0} {7 0 0} {11 0 0} {5 0 0} {6 [0] 0} {4 1 0}] [{153 8796098789376 0} {152 101534041545768960 0} {1 101534041545768960 0} {2 12386304 0} {600 0} {10 0 0} {14 17170432 0} {61 0 0} {8 0.0.0.0 0} {12 0.0.254.128 0} {7 0 0} {11 0 0} {5 0 0} {6 [0] 0} {4 31 0}]]}
setHeader.SetID: 0
len(tr.ScopeFieldSpecifiers)  = 0
len(tr.FieldSpecifiers)  = 0
data: []
 2 d.reader.ReadCount() = 215
 3 setHeader = {SetID:0 Length:64256}
setHeader.Length = 64256
 d.reader.ReadCount() = 215
 d.reader.Len() = 73
 msg: {127.0.0.1 {10 288 1549286824 95526 0} [[{153 1549286824585 0} {152 1549286822769 0} {1 840 0} {2 10 0} {60 4 0} {10 0 0} {14 0 0} {61 0 0} {8 10.0.2.15 0} {12 216.58.215.99 0} {7 0 0} {11 0 0} {5 0 0} {6 [0] 0} {4 1 0}] [{153 1549286824585 0} {152 1549286822769 0} {1 840 0} {2 10 0} {60 4 0} {10 0 0} {14 0 0} {61 0 0} {8 216.58.215.99 0} {12 10.0.2.15 0} {7 0 0} {11 0 0} {5 0 0} {6 [0] 0} {4 1 0}] [{153 8796098789376 0} {152 101534041545768960 0} {1 101534041545768960 0} {2 12386304 0} {600 0} {10 0 0} {14 17170432 0} {61 0 0} {8 0.0.0.0 0} {12 0.0.254.128 0} {7 0 0} {11 0 0} {5 0 0} {6 [0] 0} {4 31 0}] []]}
setHeader.SetID: 0
len(tr.ScopeFieldSpecifiers)  = 0
len(tr.FieldSpecifiers)  = 0
data: []
 2 d.reader.ReadCount() = 215
 3 setHeader = {SetID:0 Length:64256}
...
...
...
OOM
````

I see some bugs in code:
 - read the set data when is only header of set or padding to read
 - read the set data when setID is 0 
 - return empty fields slice without error from method decodeData

Provided fix checks rest of data to read is greater than header of flow set (2 bytes of ID and 2 bytes of length of set) and method return error when try to read setID = 0. Additionally method decodeData return error when not readed any data (as a result reader has not advanced internal slice - this is the reason of infinite loop) and return decodeSet with error after received error from decodeData.

Decoding output with my fix:
````
TestOOM
288
288
{"AgentID":"127.0.0.1","Header":{"Version":10,"Length":288,"ExportTime":1549286824,"SequenceNo":95526,"DomainID":0},"DataSets":[[{"I":153,"V":1549286824585},{"I":152,"V":1549286822769},{"I":1,"V":840},{"I":2,"V":10},{"I":60,"V":4},{"I":10,"V":0},{"I":14,"V":0},{"I":61,"V":0},{"I":8,"V":"10.0.2.15"},{"I":12,"V":"216.58.215.99"},{"I":7,"V":0},{"I":11,"V":0},{"I":5,"V":0},{"I":6,"V":"0x00"},{"I":4,"V":1}],[{"I":153,"V":1549286824585},{"I":152,"V":1549286822769},{"I":1,"V":840},{"I":2,"V":10},{"I":60,"V":4},{"I":10,"V":0},{"I":14,"V":0},{"I":61,"V":0},{"I":8,"V":"216.58.215.99"},{"I":12,"V":"10.0.2.15"},{"I":7,"V":0},{"I":11,"V":0},{"I":5,"V":0},{"I":6,"V":"0x00"},{"I":4,"V":1}],[{"I":153,"V":1549286522610},{"I":152,"V":1549286522610},{"I":1,"V":189},{"I":2,"V":1},{"I":60,"V":6},{"I":10,"V":0},{"I":14,"V":0},{"I":61,"V":0},{"I":27,"V":"fe80::1f0c:7220:b25e:ccbd"},{"I":28,"V":"ff02::fb"},{"I":5,"V":0},{"I":7,"V":5353},{"I":11,"V":5353},{"I":6,"V":"0x00"},{"I":4,"V":17}],[{"I":153,"V":1549286522610},{"I":152,"V":1549286522610},{"I":1,"V":169},{"I":2,"V":1},{"I":60,"V":4},{"I":10,"V":0},{"I":14,"V":0},{"I":61,"V":0},{"I":8,"V":"10.0.2.15"},{"I":12,"V":"224.0.0.251"},{"I":7,"V":5353},{"I":11,"V":5353},{"I":5,"V":0},{"I":6,"V":"0x00"},{"I":4,"V":17}]]}
end _ TestOOM
````

Finally I think good idea is declare type nonfatalError as a structure to avoid wall of errors below
````
IPFIX decoding error:  Multiple errors:
- can not read the data
- can not read the data
- can not read the data
- unexpected EOF
- unexpected EOF
- unexpected EOF
- failed to decodeSet / invalid setId
- can not read the data
- unexpected EOF
- unexpected EOF
- unexpected EOF
- can not read the data
- unexpected EOF
- can not read the data
- unexpected EOF
- unexpected EOF
- unexpected EOF
- unexpected EOF
- unexpected EOF
- unexpected EOF
- failed to decodeSet / invalid setId
- can not read the data
- failed to decodeSet / invalid setId
- can not read the data
- unexpected EOF
````

**Comment by mehrdadrad** [comment]
Thanks & pull request #98 merged
